server:
  port: 9696
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /solr
#告知springboot使用哪个子配置文件
spring:
  profiles:
    active: prod
#告知springboot使用jsp视图模板
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #指定数据源
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kf
    username: root
    password: root
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    solr:
      host: http://localhost:9696/solr/collection1
    mongodb:
      uri: mongodb://192.168.37.128:40000/ems
  #告知springboot  mapper文件所在位置 创建sqlSessionFactory
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
#配置分页插件
#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count